apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: dashcccpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dashcccpipelinesjavascriptdocker 
    spec:
      containers:
        - name: dashcccpipelinesjavascriptdocker 
          image: mycontainerregistry2testdashpipelines.azurecr.io/dashcccpipelinesjavascriptdocker
          ports:
          - containerPort: 8080