apiVersion : apps/v1
kind: Deployment
metadata:
  name: "azkub01-3e66"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "azkub01-3e66"
  template:
    metadata:
      labels:
        app: "azkub01-3e66"
    spec:
      containers:
        - name: "azkub01-3e66"
          image: "az2gcloudcont.azurecr.io/azkub01"
          ports:
          - containerPort: 8080